### ISSUE TITLE
module not found

### ISSUE THREAD

**Issue by QuocTrung76** [synw/django-terminal#1]
Hello, file term/commands.py import err from goerr but it does not exist, how can I fix it

Thank you!

**Comment by synw** [comment]
Hi. I did not think anyone was using this. It is old and not maintained. To solve your problem: downgrade your version of [Goerr](https://github.com/synw/goerr) to an older version. I updated it recently and it is using an old version and api in this package

Just curious: what is your use case? What are you using this for?

**Comment by QuocTrung99-Pro** [comment]
I am developing a small webpage that can use the remote terminal to tar files (.tar extension) on the server, thank you for your support.
